addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - MATRIX_BUILD=true
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "iY6zyPnJbad5EUYas4XrCbtAG/RJ3LFKBxlAoyP9ueHLWstihrP4LY4V+2jE6sdqniMzoUSIC3gMSUasfedI5l25vTgUNVKoHosIR2sTuiLllpvsaP/da5hG4CHlsFZHY+8ErE3N6jdKEcyaEG/s6retn0+DvXVI6q+bIfOPBxY09JkoU2Ry4upA4OCTQxb5OLFZn5hw5wCnMNMBGiWj6B8XziYgzsFAZsXLIP8JNZXPcxbl2YzSJ/ScXWtOrUANejdHfWBYAYUb2MOyrDiDmU+ZH8BQ0UANOfJXyGaqWfXtqlS7Sk108qys7FoXHTnwt+hTmiBM7jgzYnOPCPf7q0PNcsBCwk9V5L7U8X0yPWeHBX1X2I5rEuD3H6A2ZnmPlbfR6IaOOOYbB03xKFFFxH9YNqPJQLNfilyQ9+1BuB8KWzKP5J5oQDmcLil+jq1Dxej9Ny4oPTvUMKEt6QtxM+ipagybTjvo06sQlCfdBaTXSSh0po8E6GMY2cydpwj8bDYaBkp3Lktw2kpPFGRxeOb0Q2bElDrWXn7W2PiTFU0CQqw1hWlgKSeO8OEn3zyUCWmArGKV5QiJa7H5/US3UT1FcZtb73OSUv0QM8eHFP9HmYYFx9j3pcKq6fs08TA0l/OxaEfamk0R40hNudY+bgXB2sBZLs5kXrRntQK4LFg="
  # GITHUB_TOKEN
  - secure: "RbynCe2vk6yocJ6M809FjdJPKsaqyAoUgcSycdon+R6jiUcyYq9OmhYA5vpZiUZVgsEWD5YZwDRiGUYoREp/L7C1He1lAJ8PVdeaEYI3Zh8jE112oddzcKmKHismRrlu/oAzhdOIOKMZ4SH8J4jnehXF0db57YTi+1b+3MUYv9+FzUTJuvJjGmPxTFPcQVFU8oABy4zHSLqxAlmb8u6xb40Zo6ODz4NVeeKO+bO/yFvWt4WxI0KqOUEjYO/Vde72hUF9J41tce87QUhCKbAUcArizkIueuiNdY4o90+Vc7wFaHavtP16FuZ1K/Byz+nTcn9Eh1L2RY+0YrRjCBuWZjHNmD/ECtmlRz/pT+iGwHu9pkstqIKJMmw1/O77LuVeXvKxW5XS+Lrxu1uP1ZQFzlx6hvE4Eheu5Ousclh6ikTGsM01NimTv7YQhWa6QJ3pkJUVLbT73Ai8EpDw90BG7bQ2GHexiI2chgTtdYcxEkFAif+07TI0G86Z4/v8kDMYT+AXRzYFuhRwJqhtXj4G7wN+7XaRAHOE3zRodpk6TkI8vqJVv+20vScwz5P6CdjqpzGFwYNERhs3tzySujxoypIdnxDAlDJ965XgEmjgzDNg45tzc5mWErLaTcpsJCfaT2ec/qWnaMCW7yKk+HPBcfPFTvmrdhm7e2zmfKYyVxM="
  matrix:
  - RELEASE=debian/jessie
  - RELEASE=debian/stretch
notifications:
  email:
    on_success: never
    on_failure: always

before_install: source scripts/ci/environment.sh

install: make build

script: make test

after_success:
- ci-tag-build
- hub-push
