addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - MATRIX_BUILD=true
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "gPYqJb1uihSMaoqQ9m3ax2qWw/zymlvF+dzbmAhmz397B4CXnQ4fRmqxvkoFsv9HC1KEgtIo2dHk9Fbji6pJ1L/yc8UooxAts44T/IquPhY6MjTojK1MRpuVANyoqFrrt9k5gqE7FOEgLnpCw5Jkl4qSgjLV0G+sAHqsOSEZpfRMU9FqMy1CjJI9GHUWI8o2yebfel/HU4ejPk8jkjLSf4o261twxVcp5wY3hYvtxAYlGBoiY59qppp5sQDU6be/nVdasVcQaLY29q6lMPBvHG0K2OZy0CMO64RrDGNsmskHKQxW8+0ZNuG6vgHvB/rXaQW8sMHChjZc5ML6WTo5MwUzPaMMvkFJbgnV6VTv5X//q3o0ixFLedXYsNNW08s1zmaDZUjj/HqwXFHLa+6t5F0DE++yRB0WlsESEaUE5hn1lxMk7p/lvPyLx5lYdFeYnEVfjeLV0HCdljAWax6s2lpWpMkeK9xl4z2dLAJsi6E27FKQSJe0EpzAr8H/4ySbZ42w1zTQqaW7XAiRNR/P0tpjGU2dXN+9B0XHUCf3l0ZMUXFvUvQKgMEkyT4/gBQeMx6MwF/lmX44WFokGK6oKs4DQ8C/evjtSkQ/etTjl7mo9cXsXVaLpPJijF2M3z8ExUc1/b7oJqL3vj/hiyL3HI0kE1eW7nfTq3snWUJfWLc="
  # GITHUB_TOKEN
  - secure: "qhNtT5XtEL3y8zO0K9VwZP5WH1fO1ycK6egpkSjjXfPFuu9ykGD0MIXIJWEPIQKOulyuNM6AtpZE4etggTp02TarXcYdke74Bgr8/X+OxXWC7DidakAmLZ63Pi+Oc7elgGdovy1tD0EDuBoPkTZVhPqGkO0BZBhlk0Vr0NEHFczIFcMd4+fx4kueuV2Jmj/mA++sTw00P6hRqbRwLv39Eyhq/stzTqUvLB/glieCYVeA0PjdoGXJcjXGI8USYN7VKdb1GujeUvpQHM+JOT+o5tm78lTEoOa3Y/60LNopLIWuHrpqzDNQP9P46hh2dWD2uCUD4KmlzfDHYFYXic7GNG/ZmwHyZjgJuy9GSZbm5LLhX1X3Ow1Dw895Y8VoTEASetukAQ7i/jLF85QhMZeTTzo8rBKLrrXS0M+XzXMQLMaaUQxnAbsucYEoIzWcgzVgZnMrI9i1BMRcmYxpE5C9PvecnaVs6MPKUBUVPTj4ecMi6NQS7wam4XKeXnccvfMu3e2oxx8Y63fy3JmY1hLZwWcRzLnU2BUPIJf1WU0upswIn0lDQ6KdAHH3AIkBes/5Z6UKNBTzeUA/zWwDWz800eDaZgPkmVrgh567fnxKDQlEQlhJGacJe0oriTr0F1dNgAGIKUnFoswHdIRgV7R4rgOdwhE7kH+Ce3S3LoNOqRs="
  matrix:
  - RELEASE=debian/jessie
  - RELEASE=debian/stretch
notifications:
  email:
    on_success: never
    on_failure: always

before_install: source scripts/ci/environment.sh

install: make build

script: make test

after_success:
- ci-tag-build
# - make release
- hub-push
