language: python
services: docker
env:
  global:
  - DOCKER_USER=callforamerica
  # DOCKER_PASS
  - secure: "mMEANywuJa0mHyoNnkSI1+SFQAXsgnRqMq4Av5dr070wj55g0+XvDgohXDWIi87yGpFecKFL41JrcSBfU2Quldprr55kc9xRFMr4mINw9rp2HPwRwXNqWl2T326bRDWbEI4kmrAGOIHKPj8o0yxXUfLn6RzNsiRc87cLTJ366HinCYFBeAvP9rTaaCGRjosp2Wgs2GOon7fIimH2OBInbsELL00r4/YdkUXGoQMf94oSeN9hWx16apZ7P0NO8NmeOFKhcS+XE5z0s07YG8bqs9f5PH3NV04vot2p797Y1NN9DFyJOHqWiCuz8myCPgo2XIdhdtVX2LkSYKL7/OGzsOyCX8vu8dNSd2ddJUC8aq4FfjP9LLMNNoCIq8mT513oHPHt6yj9EidYm76hEpS3mqMZp4bf/TFde4DFhMFXXbMDq3x3r2H0/QL3ZFN92JzEZjWpVa/jjo7XKBoKTzVAiMKG+//XOjJkJtNSFRkM235xEiU0V8NQuSpCce1O82+5lgVTVNfD8MrPbY/1F3yP6MiCgNFWppv524s3UM/KHVd6SMs7ZKn83ZGq8CGe6uRr5eg+8Y295WEf5Zz2JbFpiSYhA18Ej/yQkJcyJM5VtT54BkZ4f/2wAVKtPROTtxLAN3h9flgTQSpMvxiwlIOeMmlXF/yXaElQCmMjKUdZ244="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "Wseh6udFH4p9w/XWLKlhnx81lRSA92dSdldnS59+HBvPJlr1kWCjOIPzGzNX4o0TaAmK289GQlOndFriO+O6dy1JYM4p9frECktLhp+cpEexnfVUwcAjSvaWoha9MqGnaj5CZxccsUxquy9CZqsoOp0oKTm5xSJrlYMRxxeHH3ZVUDf4LN/pt8devfTbIwK13+lYRKo66qRUtPRw2SsT+PMXIcryZ7iW7T4agy6ShxsfxcY925Cul0QQ9qxcOgBbu/8jeZqH2rKPnYxj6NCpBpbXqZnynjNmLKqTSi6heyCgXpj3FDBXxwD2Ag9QEoGfCPkz7t2EQ292Efzw4RfRiRdcLbd2SJLPVjbkI/74P4ZZd/fqQb+Q05jWvINPzExm9vcVNuKqyBkIC97NJKhICv/g3thEOMXCLrOOKBpE9RE9ygv+c3JgkN4RhCdD5zKx9/bF1e0Uw2xY0A37Hx+hDg/IkMk4rsCpcaU4a3C/fyBIY8tYJv/zXtUAK6zvPdzBjlWnNz4WZMW+LNaEf+3yLG8dQgPGqt0n6t1KpNeuLRUQ89qp75ZdNT+4m7yoKMzGi3JkMMQx2D00k64qPUhKp9wPJgQSApCE9TmGbqY35BdinSQ45y3imh632fr3lzcfvX7Qg3hx2fL71CcRiZEZaePpyvD11HneCm9jaH46i0Q="
    on_success: always
    on_failure: always

install:
- base-repo/init.sh
- base-repo/build.sh
- base-repo/build-docker.sh

script: true

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $DOCKER_USER/debian
