addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - MATRIX_BUILD=true
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "LtzoNyihCU2DPeieVHpBDk7StD2vhl7AJZtae8f433NecADCFrAjocWty03F3EZpjKDdTIJ04YSKa1O1yKzdMdqZ8tM4g0OV5HUW6Kbmgj1Ux4QtUPslqdX8G5u4l0z9FXGb054HkMyWi+IaGfqSYzUXB8ThQ0YvtdtCVRbpoS3vMHLqq2c+fX5X9cYVCSrP/7LHk030eGuxYSO+os5U6RZmwiKAfFyRTlXsfYIfAoQOiJSX7f48SQMDUyNucT76T7ZKrZjTxeSCf8W6BhLg+szaX2GbiOSTUcCGxqq8quDf3BQb117vkG6F80V+HKCz9cpD9KthVpf8R/8id6r3GHQpUj+nfg/PxSqc5+7a6a7kyukUFOlpPlDvFdkzBTG8xMlxgAZFfDaVDaPxpUss3dIgpSU30Np2jA4sneLss+epuH621LRcnPgL5v5pslqZC+9RGWE/TVnoxytzttyPFuSIFWbRxW7uLkRMLVLsVye0lPvYm83ILGrp1ULcX5H5+k+OhPVapaN2ezZYCV2RvLmoHRAXMUjN6qGz3DpsilzbMhH9ZQdRxpv6EuPY11zseUxqNDINbXOjcQ6jQRpkQygCnCP2D3Tw7CG4KBuOw0LIoX9xcV9j8cmqAZwcOzSw618SyFze5onOVUHnzhd8Lyx9upIp7XUSyJfudKFqqic="
  # GITHUB_TOKEN
  - secure: "c7Y36NOyVvBFCjmrqPTP/gN+LQo7GxtF/2XkjswJX1Af6VISlc50jjxLpkZIxaqU83H3jrRDhZTNa7KaNQpUgbPYqJqWfjHmcNNOfB+jzKM39b0oFbzVE/Gv/BqjsftS7mCSJq/p6KkjM0lnBjB6/2QfzWp672k/FtLryfdtS86z7lXJhtxYchMZ6awg0IzaY7eW22GyiBuRbsa3fgu3Ii5b1sc0AyvC3kbcehSEBgwaH9JCHGbw3ui3p+ipI/bzCEXY/e5Myde+4FZTarXVcVfhV/9qkykEFYmG8aDiiKiKKV2N0b96ExUGh/3+uDUcx6rWS508tWXueFNiiH3Tlc5H4Xiig2lk9P0lqRLl6ErszJtsFCJh+y+rb+4irayXX/I2voJd6HuGLlBGLXyIeJ4YAs+qxX8UXjthtfve59Yl+86ANq8fXEERF7L/I0leGQbJzz64rame0MbTF9N/JjQ6bMA7fE+bMreXmFjQJh5qT0cQXBzk/XfdIvfOUzCnmP+OKIJ01d1C74RI1w9nBXLQI6WjWDd03+fzxcr6WqPjTizK9DfzLBBuwozB6XXArx+Pzp/6bJklB73VJCdfa7gRAneP6YYxOVRwzm0vf0GYA69egVR5uBmbXiKKcY9zmkhjK+ETGX7MrsjoDAXylD+J59MlL1BQfNxKgd+NC00="
  matrix:
  - RELEASE=debian/jessie
  - RELEASE=debian/stretch
notifications:
  email:
    on_success: never
    on_failure: always

before_install: source scripts/ci/environment.sh

install: make build

script: make test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme
