addons:
  apt:
    packages:
    - realpath
services: docker
env:
  global:
  - DOCKER_USER=callforamerica
  # DOCKER_PASS
  - secure: "IQG+QuyQrN7PCnU6OCNbshX0KPSWHCPRYoj7Ga0kmgR0RUk1tbYihL870iDvL2cMUcQmgZRwBQOvAvECzCA7FOtsqFvQ4RjHPTgIFyd6NWm/5Rvb6uun3yAXwJ9fl9sq0lDJdvPOyowITnltYMd1b8hASBUR/S4JDOGZItaYAnFfTE/PkIp2vOgCos/F474c86v9AeJJJTmCMGEJUI1X3hYO/KCkvWcKpLnkvm+KO/aY84LTXJu+3iZ4rq3DVms3IFFBEtH2rpUGvP4saDB1JNvEYw6VoO6ZEyJIVpOpWgq0BZGa3nQ8ilN1lMWtwWJajsqJqXG91ILR0b1tZJEQRnjPHK1hYG3S1v1J3BlKXFDEqLVKTLfOHfSMyC648+d0Z9YQBVkuXpszfYpNmj1lDCS4tN+UwOZjgsDYaXHSmiFhhEqnuSJ6H2ZSxx5iPue4crkLLWf7rpgKX/PIrxA8rv5lY+zUY6u+iNWsSyILj0w6AyvpaeZNDz3dQR3zm21vLYvcMa91Ic56EZckQPs3KjLD8ult4/qWzjT3uRE+5N8KyBXX+o5Mw4Dk/rrkZOaHo8aktzEIguOsykAz8WMq0u0F2JrqECW1cFfWHaTSBDF4+StFrWQ4jnJ4HaUcuJIY47Ubz0kpiG6ZrQEkyBjDwvFLfXM0Mg592f4NWepSLUw="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "IIUF/11EoCuFcsvuZwBBJSImI4nzCEQCwi29yQVRRptT8rXqMid7I3UvAsMrzhsp4Qlp09a/rDwPKBmoZcyV3DPzvUfOU85RwaCWCBZ3AGt2Jf7evhPw54rkRBTn+XnP8xmal6TYXcWqgvhU5BjLbTZciH+j0wqMl3lL4dhBkzlYNdgfl7qg9hvBs5AL//d/z33bUMxC+XO8l7z7qzPShGX47OZ+m4YsdwIAii7Ro10ofVCGYTqrU8y02FJ/CtLay8O+kfh7/tTFQA8U3t2sMyofT6Y7T2CGL49s9R+TWavczq34zenmoW/zoTi+AYtZ6MqzdnxOUIM/pNURrOSJxDt6YHSDEH6ZnP56sJwk7uHBrT6dJk1lGe8fzwqXvmpwTgFuEcoCdbrzBwNEtm5iONTzRGWZxQH3xC7uNicNaMTVMHvqySrJ7epkC9RHz09stf0zsl3DPtF/7/K6p0Cttttp/I0ogLG1o2/xEuU1ee0eKwKGB6Q+w+++Kw8c5h419oFU+QHaqGeQEkojeiM+26R+pJlarxzlnQMog1hmqQW07ZlAjEZXxRKBxPnk7Lg1iXDAjvs9dfDhzG///Wl7jLl536qE+hUs5lzSzVJ3fjjAaGfSj+7gu66mHkItTEgbbwdu7iBEK2JN/RvAjtBLuLMRZ+KnxZRNoX2lwF950iU="
    on_success: always
    on_failure: always

install:
- base-repo/init.sh
- base-repo/build.sh
- base-repo/build-docker.sh

script: true

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $DOCKER_USER/debian
