addons:
  apt:
    packages:
    - realpath
language: python
services: docker
env:
  global:
  - MATRIX_BUILD=true
  - GITHUB_USER=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  # DOCKER_PASS
  - secure: "OUQmMtN18kFHVO8539eb8xki0jRptregR6tPh7i2Tfou9VSx+013DiXOksH4V3/A8IiWVLGYt+dzqyWD/476s2a6myWQmRlrVqHsH3uMPMa/TxEWioG2lkmjQlrixH1ZLSe0mMEVyRXQNmXNYv3Om1Z6E4yrfqlLN1CRrEHjs1+qrn8VXMVp91oHtquaR69r7gITdHTB07rnTZkQbMFb8w/xUcCi8zUJwKYTlo7qN3e+0zPhsHvAqaOsZWb1kBtwPn3Un/lwMyISIKra16QS2c7wUN226DQAGwbWXDWTQ+kEG1kdwLV8yC+mP/x3lA2rB0DkAIQsDHoXTaGK5Nq2z8gpy3RROiKT+2ofgYuRXCWWSLkZLwwrrddEH2qJbW6Trd0WuxAbbtEB9Pv0KnUccw4W0FGwvIsaeELS1WVBgBZlyHndTN4lH9dxMxB5vDHd14YV8SNA7OVyhzGAq4/CIQMlJBfh2gZzvWJxQAailDwh98XYUy+bwzTvUSMdbZJUIwlDvlAj9Zj2D4WTYUL3//bVQCzKVTmm2/o0F1NCBCK5l/Bq97x27tftcx53V47FOYQXvEQ4BLKYjRZVlgm+LBeiCi2xQv6wYaWu1kylhRT6lHefOIVCKNjCPhlu3qyoQTuNEvmTB9DH/pYyOqVPlH9yPahTaiZVXVzRo7TPOO0="
  # AUTH_TOKEN
  - secure: "YjsB3IIXa8HOr2VIILG7DkEPpEcEwk3ppVJkTOfgN3rENXMDJTgn3RZC5C/ajn98qRPCEKNoZe+bS34MeZotN2nx5ceUcqf8yznH5wYrwLQ4Ozpl+ry/4Muk/11w4dXYdx7cMHw/68M7MfLiVodBw1BYK3yllkRGJCTsyJdOaWvQgY6zcps2JL0k6dd3TTfQqMFqzj8J1cTNziMRTLH2m81I+8aCneM4LNGWQ8RqTBj7soPif/VMDmybrUW00TfwahKKyq5+qQs34OwrgygKz4YGiTRBFNrRZvoS9srwAC3j5mP/ewnmJxA1t9v1QlwUIwByxoaxuJmYBggZUUj61cMVAxzPaILCvecZSn5EwmviTmJuXUQgtOeu/6F5+Zm5CtLv1HJktw+MDC1jNWHy+cEMWDrrdAWAlsY3yoAD1Z20McRbNlNAKaWu9AmT/R115k6U8curT9Erc+0GYEKjQ5AYvDdNE6KE8eTI6xKK907N+CXAJAcRlb8aSXHNxifOkWQAx8XZE3zelIXeWY+QxYY3pG5Qk54A8DnwXuoE3KPjnShSnAZUVQ1km7zIHqRLZHGwG4UW18+pKBYNLJbzjPvtUsrQme9VQrhkmbWU3fuFXib594vAnm7rZGlpUgwOKeRVwtXZazuHir2Lef1SGwEqshC89oue5ueSM5FihWs="
  matrix:
  - RELEASE=debian/jessie
  - RELEASE=debian/stretch
notifications:
  email:
    on_success: never
    on_failure: always
  # slack:
  #   rooms:
  #   - secure: "IIUF/11EoCuFcsvuZwBBJSImI4nzCEQCwi29yQVRRptT8rXqMid7I3UvAsMrzhsp4Qlp09a/rDwPKBmoZcyV3DPzvUfOU85RwaCWCBZ3AGt2Jf7evhPw54rkRBTn+XnP8xmal6TYXcWqgvhU5BjLbTZciH+j0wqMl3lL4dhBkzlYNdgfl7qg9hvBs5AL//d/z33bUMxC+XO8l7z7qzPShGX47OZ+m4YsdwIAii7Ro10ofVCGYTqrU8y02FJ/CtLay8O+kfh7/tTFQA8U3t2sMyofT6Y7T2CGL49s9R+TWavczq34zenmoW/zoTi+AYtZ6MqzdnxOUIM/pNURrOSJxDt6YHSDEH6ZnP56sJwk7uHBrT6dJk1lGe8fzwqXvmpwTgFuEcoCdbrzBwNEtm5iONTzRGWZxQH3xC7uNicNaMTVMHvqySrJ7epkC9RHz09stf0zsl3DPtF/7/K6p0Cttttp/I0ogLG1o2/xEuU1ee0eKwKGB6Q+w+++Kw8c5h419oFU+QHaqGeQEkojeiM+26R+pJlarxzlnQMog1hmqQW07ZlAjEZXxRKBxPnk7Lg1iXDAjvs9dfDhzG///Wl7jLl536qE+hUs5lzSzVJ3fjjAaGfSj+7gu66mHkItTEgbbwdu7iBEK2JN/RvAjtBLuLMRZ+KnxZRNoX2lwF950iU="
  #   on_success: always
  #   on_failure: always

before_install: source scripts/ci/environment.sh

install: make build

script: make test

after_success:
- ci-tag-build
# - make release
- hub-push
